from src.utils import Vec

WIDTH, HEIGHT = 1280, 720
SIZE = Vec(WIDTH, HEIGHT)

BLOCK = 64
CHUNK = 8
BLOCKCHUNK = BLOCK * CHUNK
BLOCKXY = Vec(BLOCK, BLOCK)
CHUNKXY = Vec(CHUNK, CHUNK)
BLOCKCHUNKXY = Vec(BLOCKCHUNK, BLOCKCHUNK)
