from src.utils import Vec

WIDTH, HEIGHT = 1280, 768
SIZE = Vec(WIDTH, HEIGHT)

BLOCK = 64
CHUNK = 8
BLOCKCHUNK = BLOCK * CHUNK
BLOCKXY = Vec(BLOCK, BLOCK)
CHUNKXY = Vec(CHUNK, CHUNK)
BLOCKCHUNKXY = Vec(BLOCKCHUNK, BLOCKCHUNK)
CHUNK_CHECK_MAX_FREQ = 20
CHUNK_LOAD_MAX_FREQ = 1024
